design: 로그인 레이아웃
Likelion-YeungNam-Univ/12th-holing-web pull request #14
Opened 2024-07-27 15:38 UTC by juiuj

![스크린샷 2024-07-28 오전 12 25 53](https://github.com/user-attachments/assets/3025c1c3-2b21-4cce-b883-cae323f62a13)
`/intro` 경로로 이동시 서비스 소개와 함께 `카카오로그인` 을 클릭할 수 있도록 구현하였습니다.

![스크린샷 2024-07-28 오전 12 26 29](https://github.com/user-attachments/assets/77b7b83d-3326-47ab-bf64-b2efce08362b)
`/share-url`경로로 이동시 짝꿍에게 url을 공유할 수 있는 페이지를 제작하였습니다
* 추후 url 공유 기능 추가 및 자가테스트 결과 api 연결 예정입니다

![스크린샷 2024-07-28 오전 12 26 09](https://github.com/user-attachments/assets/3529c36d-6a5b-437f-a4a8-f4e779cedc67)
로그인 성공 전까지 보여지는 로딩 중 화면이며 경로는 `/auth/signin` 입니다.

**Note**
* 현재 로그인 구현 부분에서 오류가 발생하여 우선 디자인한 부분만 push 해 두었습니다
* components/login/Callback 에 우선 구현한 부분까지 저장해두었습니다

2024-07-27 16:48 UTC, JO-MINSEO commented on src/components/login/Callback.js
> +      localStorage.removeItem('oauth_state');
키 이름을 auth_state로 통일해야 할 것 같습니다!

2024-07-27 16:55 UTC, JO-MINSEO commented on src/components/login/Callback.js
> +    const REDIRECT_URI = 'http://43.201.5.161:8080/auth/token';
Key 값이나 Uri는 github에 안 올리시는 게 좋을 것 같습니다...!

2024-07-28 11:18 UTC, juiuj commented on src/components/login/Callback.js
> +      localStorage.removeItem('oauth_state');
`auth_state`는 사용자가 인증된 상태인지, 또는 현재 인증 과정 중인지 등을 나타내고, 
`oauth_state`는  클라이언트와 서버 간의 요청이 일치하는지 확인하는 데 사용되기 때문에 구분지었습니다!

2024-07-28 11:18 UTC, juiuj commented on src/components/login/Callback.js
> +    const REDIRECT_URI = 'http://43.201.5.161:8080/auth/token';
앗 넵! 수정하겠습니다 피드백 감사합니다!!

2024-07-28 13:45 UTC, JO-MINSEO approved these changes
수고하셨습니다!!!

2024-07-31 14:34 UTC, JO-MINSEO commented on src/apis/Cookies.js
> +export default Cookies;
해당 코드가 api를 사용하는 게 아니어서 파일 위치를 고민해봐야 할 것 같습니다!

2024-07-31 14:34 UTC, JO-MINSEO submitted a review, later dismissed
로그인 구현하느라 고생 많으셨습니다!

2024-07-31 14:49 UTC, immms requested changes
파일 작명은 컨벤션 참고하시면 일관성 있고 좋을 것 같습니다. 공통적으로 쓰게 되는 파일은 어떤 기능을 담당하는 지를 쉽게 파악할 수 있도록 작명 하면 팀원들에게도 도움이 될 것 같습니다. 
또한 코드에서 수정이 필요한 부분이 보입니다. 수정하여 다시 pr 부탁드립니다. 로그인 구현하시느라 수고 많으셨습니당 : )

2024-07-31 14:49 UTC, immms commented on src/App.js
> +              <Route path="/kakaologin" element={<ShareUrl />} />
`<Route path="/" element={<IntroFrame />}>` 안에 해당 코드를 넣으면 테스트 프레임이 아닌, 로고 프레임이 씌워지게 됩니다.

2024-07-31 14:49 UTC, immms commented on src/apis/home/medicineNote/medicinePost.js
> +      Authorization: authToken,
authToken은 더이상 .env 파일에서 불러오는 방식으로 사용되지않고,  getCookie 를 사용해 토큰값을 불러오는 방식으로 바꾸시면 됩니당

2024-07-31 14:49 UTC, immms commented on src/components/login/LoginButton.js
> +// };
사용하지 않는 주석 처리된 코드는 삭제하는 것이 좋을 것 같습니다

2024-07-31 14:49 UTC, immms commented on src/components/login/ShareUrlPtn.js
> +import ShareLink from '../../hooks/login/ShareLink';
절대경로로 수정 부탁드립니당

2024-07-31 14:49 UTC, immms commented on src/components/login/ShareUrlPtn.js
> +  };
`copyUrlToClipboard`  메서드 로직이 궁금합니다

2024-07-31 14:49 UTC, immms commented on src/components/login/Token.js
토큰에 대해 어떤 기능을 작성한 것 인지를 잘 나타나도록 파일 작명을 하면 더 좋을 것 같습니당

2024-07-31 14:49 UTC, immms commented on src/pages/ShareUrl.js
> +      const apiUrl = 'http://43.201.5.161:8080';
서버 url은 노출되지 않도록 .env 파일에서 불러오도록 수정부탁드립니다.

2024-07-31 14:49 UTC, immms commented on src/styles/home/SharePtn-styled.js
> +export const CloseBtn = styled.div`
위의 ShareBtn 스타일 컴포넌트와 공통된 속성이 많아 보입니다. 공통스타일링을 변수로 지정해서 사용하면 코드의 길이도 줄고 효율적일 것 같습니다!

2024-08-01 10:16 UTC, juiuj commented on src/components/login/ShareUrlPtn.js
> +  };
` const currentUrl = window.location.href;` 를 통해 현재 페이지의 url을 가져와서 `navigator.clipboard.writeText`를 사용해서 url을 클립보드에 복사하는 형식입니다!

2024-08-01 13:42 UTC, juiuj commented on src/styles/home/SharePtn-styled.js
> +export const CloseBtn = styled.div`
`BtnStyles` 지정하였습니다!

2024-08-01 14:01 UTC, juiuj commented on src/components/login/LoginButton.js
> +// };
수정완료하였습니다!

2024-08-01 14:04 UTC, juiuj commented on src/components/login/ShareUrlPtn.js
> +import ShareLink from '../../hooks/login/ShareLink';
수정완료하였습니다!

2024-08-01 14:05 UTC, juiuj commented on src/components/login/Callback.js
> +    const state = searchParams.get('state');
해당 코드는 불필요한 코드라 삭제하였습니다!

2024-08-01 14:10 UTC, merged