Calendar  API 적용 및 기능 구현
Likelion-YeungNam-Univ/12th-holing-web pull request #2
Opened 2024-07-17 15:52 UTC by JO-MINSEO

**1. Full Calendar API 적용**

<img width="461" alt="image" src="https://github.com/user-attachments/assets/f679fc39-889a-4041-8972-86b02317fd23">

**2. 기능 1: 캘린더 내의 날짜 클릭 -> 일정 날짜 변경**

![image](https://github.com/user-attachments/assets/2f102654-8198-4c5a-93f1-302aca8a5322)

```
    const handleDateClick = (info) => {
      setSelectedDate(info.dateStr);
    };

    calendar.on('dateClick', handleDateClick);
```

캘린더 내의 날짜 클릭 시 handleDateClick 이용해 일정란의 날짜가 변경되어 연동되도록 구현 했습니다.

**3. 기능 2: 캘린더의 버튼 클릭 -> 날짜 설정할 수 있는 팝업 창 구현 -> 일정 날짜 변경**

![image](https://github.com/user-attachments/assets/b62e2f80-b855-4340-a06b-8d72fec03067)

```
  const handleWheel = (event, unit) => {
    event.preventDefault();
    let newDate;
    if (unit === 'year') {
      newDate = addYears(date, event.deltaY < 0 ? 1 : -1);
    } else if (unit === 'month') {
      newDate = addMonths(date, event.deltaY < 0 ? 1 : -1);
    } else if (unit === 'day') {
      newDate = addDays(date, event.deltaY < 0 ? 1 : -1);
    }
    setDate(newDate);
  };
```

onWheel 속성을 이용해 팝업 창에서 날짜를 선택할 수 있게 구현했습니다.
선택 날짜에 따라 일정란의 날짜가 변경되도록 구현했습니다.
팝업 선택 날짜에 따라 달력이 해당 주 or 달로 변경되는 것은 추후에 구현 예정입니다.

**4. 기능3: Calendar Toggle Button 클릭 -> Calendar 주 단위 or 월 단위로 변경** 

![image](https://github.com/user-attachments/assets/799bb1ce-b629-4bd5-8b96-1dbab05d6221)
  
```  const toggleView = () => {
    const newView =
      currentView === 'dayGridMonth' ? 'dayGridWeek' : 'dayGridMonth';
    setCurrentView(newView);
    const calendar = calendarRef.current.getApi();
    calendar.changeView(newView);
  };
  ```

Calendar Toggle Button 클릭 시 주단위-> 월단위, 월단위->주단위로 변경되도록 구현했습니다.

기능부터 먼저 구현하고 있어 아직 style 구현은 하지 못했습니다.

2024-07-17 16:40 UTC, immms requested changes
ci 오류해결하고 다시 pr해주세요

2024-07-17 16:47 UTC, immms requested changes
ci 오류해결합시당~

2024-07-17 17:16 UTC, immms requested changes
각 메서드나 훅에 대해 간략한 주석이 추가되면 팀원들의 이해에 더 도움이 될 것 같습니다.  노션에 작성된 컨벤션 참고하시면 좋을 것 같습니다!  디렉토리 이동이 필요한 파일도 보입니다 수정해서 다시 pr부탁드립니다. 수고하셨습니당 :)

2024-07-17 17:16 UTC, immms commented on src/components/Calendar/MyFullCalendar.js
MyFullCalendar.js 파일은 페이지를 담당하는 건가요?? 만약 컴포넌트가 아니라 페이지라면 `pages` 디렉토리로 옮기시는게 좋을것 같습니다!!

2024-07-17 17:16 UTC, immms commented on src/App.js
> +            <Route path="/Calendar" element={<MyFullCalendar />} />
보통 uri는 소문자를 사용하기 때문에 /calendar가 더 적합할 것 같습니다! 추후에 api 명세가 완료되면 또 바뀔 수 도 있겠네욥!

2024-07-17 17:16 UTC, immms commented on src/components/Calendar/MyFullCalendar.js
> +  }, []);
훅 관련 코드는 `hooks` 디렉토리에 분리해서 import해서 사용하면 더 깔끔하고 좋을듯합니다!

2024-07-18 08:34 UTC, JO-MINSEO commented on src/components/Calendar/MyFullCalendar.js
넵 pages 디렉토리로 옮기겠습니다!

2024-07-18 08:36 UTC, JO-MINSEO commented on src/App.js
> +            <Route path="/Calendar" element={<MyFullCalendar />} />
넵 calendar로 바꾸겠습니다!

2024-07-18 08:38 UTC, JO-MINSEO commented on src/components/Calendar/MyFullCalendar.js
넵 앞으로 주석 추가해서 PR 올리겠습니다. 감사합니다!

2024-07-19 05:29 UTC, immms approved these changes
너무 수고많으셨습니당~~!!

2024-07-19 06:19 UTC, merged