Feature/medicine note
Likelion-YeungNam-Univ/12th-holing-web pull request #4
Opened 2024-07-19 12:55 UTC by juiuj

test

2024-07-19 18:55 UTC, jinlee1703 commented on src/components/home/symptomTest/SymptomTest.js
> +import { SymptomTestBtn } from '../../../styles/home/SympomTest-styled';
해당 참조 방식을 `상대경로`라고 하는데요. `import deep from '../../../../../../../A/B/C/file.js';`와 같이 상대 경로가 엄청나게 길어지면 어떠한 일이 일어날 지 생각해봅시다 ㅎㅎ

2024-07-25 06:10 UTC, immms requested changes
수정 부탁드립니당~~

2024-07-25 06:10 UTC, immms commented on src/components/home/medicineNote/MedicineList.js
> +
약 체크 하는 역할의 메서드인가요?

2024-07-25 06:10 UTC, immms commented on src/components/home/medicineNote/MedicineList.js
> +  const [medi, setMedi] = useState([
훅 관련 코드는 hooks 디렉토리에 분리하는 게 좋아보입니당

2024-07-25 06:10 UTC, immms commented on src/components/home/medicineNote/Modal.js
Modal.js 코드 전체적으로 로직에 대한 설명이 없어서 파악하기에 어려움이 있습니다. 간단한 주석 부탁드립니다.

2024-07-25 06:10 UTC, immms commented on src/styles/home/MedicineList-styled.js
> +  font-family: Pretendard;
중복된 코드 수정 부탁드립니당

2024-07-25 06:18 UTC, JO-MINSEO commented on src/components/home/medicineNote/MedicineList.js
> +  };
메서드 기능에 대한 간단한 주석을 달아주시면 이해하기 더 좋을 것 같습니당

2024-07-25 06:21 UTC, JO-MINSEO commented
수고하셨습니다!

2024-07-25 07:40 UTC, juiuj commented on src/components/home/medicineNote/MedicineList.js
> +
네! 약 복용 완료 상태를 체크하는 역할의 메서드 입니다

2024-07-25 07:43 UTC, juiuj commented on src/components/home/medicineNote/MedicineList.js
> +      completed: false,
맞습니다. 이 코드에서는 true면 해당 약 복용 완료, false이면 아직 완료되지 않았음을 의미합니다!

2024-07-25 07:44 UTC, juiuj commented on src/components/home/medicineNote/Modal.js
수정완료하였습니다!

2024-07-25 07:44 UTC, juiuj commented on src/styles/home/MedicineList-styled.js
> +  font-family: Pretendard;
수정완료하였습니다!

2024-07-25 07:44 UTC, juiuj commented on src/components/home/medicineNote/MedicineList.js
> +  };
수정완료하였습니다!

2024-07-25 08:01 UTC, immms approved these changes
수고 하셨습니당~~!!

2024-07-25 08:01 UTC, immms commented on src/components/home/medicineNote/Modal.js
> +  }, [isOpen]);
모달이 열릴때 스크롤을 막는 효과가 어떤 것인가요??

2024-07-25 08:02 UTC, merged