Calendar 페이지 디자인 & 마이페이지
Likelion-YeungNam-Univ/12th-holing-web pull request #6
Opened 2024-07-22 06:31 UTC by JO-MINSEO

**1. Calendar Month view, pop up 버튼, toggle 버튼**

<img width="428" alt="image" src="https://github.com/user-attachments/assets/09c5bf92-7ba6-4c81-9a36-14d239c9617c">

**2. Calendar Week view**

<img width="443" alt="image" src="https://github.com/user-attachments/assets/f7f1e556-cbcc-434d-90af-bd1910986a14">

**3. Calendar 날짜 설정 팝업**

<img width="299" alt="image" src="https://github.com/user-attachments/assets/97428349-bb7c-4381-b6f4-3a9dc6a9244b">

**4. 일정** 

<img width="425" alt="image" src="https://github.com/user-attachments/assets/f7472bd7-45ff-46e9-bfad-19f5c7e20dd5">

**5. 일정 설정 팝업**

<img width="300" alt="image" src="https://github.com/user-attachments/assets/ea7d5ccb-bbc3-40ef-b824-c1bfed49d069">

**6. 미션** 

<img width="418" alt="image" src="https://github.com/user-attachments/assets/0c3691a5-b647-4459-8492-09cdb5be64ab">

**7. 마이 페이지**

<img width="491" alt="image" src="https://github.com/user-attachments/assets/7b8f5313-cf91-4232-8f3d-5a01c133fa88">
4개의 광고 이미지가 랜덤으로 렌더링되도록 하였습니다.

<img width="458" alt="image" src="https://github.com/user-attachments/assets/ec742bf3-ca20-4f53-8d14-d840344ddd2b">

마이페이지 제작을 calendar branch에서 해버렸습니다....
죄송합니다.....
브랜치 잘 보고 하겠습니다....

2024-07-22 16:18 UTC, immms requested changes
스타일 적용이 매우 잘 된 것 같고, 많은 양 개발 하시느라 수고하셨습니다~!!
그리고 몇몇 페이지에는 주석이 필요해 보입니다. 컴포넌트나 메서드, 훅이 각각 어떤 역할인지와 간략한 로직을 더해주면 팀원들의 이해에 더 도움이 될 것 같습니다. 간략히 주석 첨가 부탁드립니당.

2024-07-22 16:18 UTC, immms commented on src/components/calendar/SchedulePopUp.js
> +};
이 메서드의 로직이 궁굼합니당

2024-07-22 16:18 UTC, immms commented on src/pages/MyPage.js
> +    },
이 데이터들을 나중에 서버에서 받아온다면 괜찮지만, 혹시나 프론트 측에서 관리해야 하는 데이터라고 가정한다면, 형식을 메서드로 만들어서 관리하는 방법이 더 좋을 것 같습니다.
const createCreditItem = (img, title, description, price) => ({ img, title, description, price });
이런식으로 메서드를 만들어놓으면, 유지보수나 가독성에도 좋을  것 같습니당

2024-07-22 16:18 UTC, immms commented on src/styles/calendar/DatePopUp-styled.js
> +export const DatePopUpSaveBtn = styled.button`
바로 아래의 `DatePopUpCancelBtn` 컴포넌트와 겹치는 속성이 많은데, 이럴때는 공통속성을 스타일로 지정해놓고 갖다쓰면 굉장히 편리합니다!  예를 들자면  cosnt popupStyle = css 안에 공통속성을 작성하고, 다른 컴포넌트 내에서는 `${popupStyle }` 해주면 됩니다! 이 외에도 전체적으로 많이 사용되는 display : flex와 align-items, justify-contents를 반복적으로 쓰는 경우가 많은데 이것도 똑같이 해주면 좋습니당~~

2024-07-22 18:11 UTC, JO-MINSEO commented on src/styles/calendar/DatePopUp-styled.js
> +export const DatePopUpSaveBtn = styled.button`
넵 공통 속성 스타일 적용해서 변경했습니다!

2024-07-22 18:19 UTC, JO-MINSEO commented on src/components/calendar/SchedulePopUp.js
> +};
react-modal api를 사용하였습니다.
isOpen이 false일 경우 렌더링 하지 않고 isOpen이 true일 경우 Modal component 즉, 자식 컴포넌트인 SchedulePopUpContent 컴포넌트를 렌더링 합니다.
onClose 함수는 팝업을 닫기 위한 함수로 사용하였습니다

2024-07-22 18:19 UTC, JO-MINSEO commented on src/components/calendar/Mission.js
> +          <MissionTitle2>미션</MissionTitle2>
넵 적용해서 사용하겠습니다!

2024-07-22 19:20 UTC, JO-MINSEO commented on src/pages/MyPage.js
> +    },
넵 createCreditItem 메서드로 변경하였습니다!

2024-07-22 19:39 UTC, JO-MINSEO commented
꼼꼼한 리뷰 감사합니다! 훅이나 컴포넌트 관련해서 주석 추가하였습니다. 주석에 더 신경 써보도록 하겠습니다!

2024-07-23 05:30 UTC, immms approved these changes
수고 많으셨습니당~~!!

2024-07-23 06:21 UTC, merged